server:
  port: 8000
  servlet:
    contextPath: /estore_zone_service/api/v1
spring:
  application:
    name:  estore-zone-service 
  datasource:
    driverClassName:  com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/estore_zone_database
    userName:  root
    password:  Yellow#123
  jpa:
    hibernate:
      ddl-auto:  update  
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql:  true   

